from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
INDEX=ROOT/'index.html'
MARK='// === VD2 CUTFORM GAMEPLAY HUD ============================================='

HELPERS=r'''// === VD2 CUTFORM GAMEPLAY HUD =============================================
const VD2_HUD_VERSION='VD2.0.0';
let vd2CompetitiveStatus={kind:'',text:'',tone:'neutral'};
function vd2HudPanel(x,y,w,h,fill,stroke,shadow=true){const p=vd1Palette();ctx.save();if(shadow&&!save.settings.highContrast){ctx.fillStyle=p.shadow;ctx.globalAlpha=.24;ctx.fillRect(x+4,y+5,w,h);ctx.globalAlpha=1}ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.strokeStyle=stroke;ctx.lineWidth=save.settings.highContrast?3:1.5;ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.restore()}
function vd2CutStatus(){const p=vd1Palette();if(!sim.cut)return{label:'CUT READY',color:p.inkMuted};const clear=sim.currentCutClearance();if(clear==null)return{label:'CUT ACTIVE',color:p.accent};if(clear<=10)return{label:`DANGER ${Math.max(0,clear).toFixed(0)} PX`,color:p.danger};if(clear<=28)return{label:`TIGHT ${clear.toFixed(0)} PX`,color:p.accentAlt};return{label:`SAFE ${clear.toFixed(0)} PX`,color:p.success}}
function vd2ModeName(){return activeRunMode==='daily'?'DAILY':activeRunMode==='challenge'?'DUEL':state==='replay'?'REPLAY':'STANDARD'}
function vd2Wrap(text,maxWidth,font){ctx.save();ctx.font=font;const out=[];let line='';for(const word of String(text||'').split(/\s+/)){const q=(line+' '+word).trim();if(line&&ctx.measureText(q).width>maxWidth){out.push(line);line=word}else line=q}if(line)out.push(line);ctx.restore();return out}
function vd2DrawCompetitiveStrip(){if(!vd2CompetitiveStatus.text)return;const p=vd1Palette(),tone=vd2CompetitiveStatus.tone==='danger'?p.danger:vd2CompetitiveStatus.tone==='alt'?p.accentAlt:p.accent;ctx.save();ctx.fillStyle=tone;ctx.fillRect(40,134,5,7);ctx.fillStyle=p.onSubstrate;ctx.globalAlpha=.74;ctx.font='700 9px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText(vd2CompetitiveStatus.text,52,141,615);ctx.restore()}
function drawTutorialHud(){const p=vd1Palette(),title=tutorialStage===1?'COLLAPSE':tutorialStage===2?'DIVIDER':tutorialStep==='setupDivider'?'SETUP':'USE THE SETUP',x=40,y=42,w=640,h=88;ctx.save();vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=p.accentAlt;ctx.fillRect(x,y,7,h);ctx.strokeStyle=p.line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+170,y);ctx.lineTo(x+170,y+h);ctx.moveTo(x+500,y);ctx.lineTo(x+500,y+h);ctx.stroke();ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('TRAINING',x+20,y+21);ctx.fillStyle=p.ink;ctx.font='800 22px system-ui,sans-serif';ctx.fillText(`LESSON ${tutorialStage}/3`,x+20,y+52);ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('OBJECTIVE',x+190,y+21);ctx.fillStyle=p.ink;ctx.font='900 29px system-ui,sans-serif';ctx.fillText(title,x+190,y+58,285);ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('RUN STATE',x+520,y+21);ctx.fillStyle=p.accentAlt;ctx.font='800 12px system-ui,sans-serif';ctx.fillText('PRACTICE',x+520,y+44);ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('NO SCORE',x+520,y+64);ctx.restore()}
function vd2HudAudit(){const p=vd1Palette();return Object.freeze({version:VD2_HUD_VERSION,theme:p.theme,flatPanels:true,neonHud:false,glowTypography:false,canvasCompetitiveStatus:true,modifierCards:'physical',milestoneCards:'physical'})}
try{Object.defineProperty(window,'VoidcutHUD',{value:Object.freeze({version:VD2_HUD_VERSION,audit:vd2HudAudit}),enumerable:true,configurable:true})}catch{window.VoidcutHUD={version:VD2_HUD_VERSION,audit:vd2HudAudit}}
'''

REPL={
'updateChallengeHud':r'''function updateChallengeHud(){ui.challengeHud.classList.add('hidden');ui.challengeHud.classList.remove('daily-mode');vd2CompetitiveStatus={kind:'',text:'',tone:'neutral'};if(state!=='play')return;if(activeRunMode==='daily'){const d=(save.daily&&save.daily.date===activeDailyKey)?save.daily:defaultDaily(),key=activeDailyKey||d.date||dailyKeyUTC(),best=d.bestScore?d.bestScore.toLocaleString():'—';vd2CompetitiveStatus={kind:'daily',text:`DAILY / ${dailyDateLabel(key).replace(/ • /g,' / ')} / ATTEMPT ${d.attempts||1} / BEST ${best}`,tone:'alt'};return}if(!activeChallenge||!challengeAnalysis)return;const target=competitivePaceAt(challengeAnalysis,sim.runElapsed),delta=sim.score-target.score,sign=delta>0?'+':'';vd2CompetitiveStatus={kind:'duel',text:`DUEL ${sign}${delta.toLocaleString()} / YOU ${sim.score.toLocaleString()} / PACE ${target.score.toLocaleString()} / CH ${sim.chamber}:${target.chamber}`,tone:delta>=0?'accent':'danger'}}''',
'drawGameplayWordmark':r'''function drawGameplayWordmark(){const p=vd1Palette();ctx.save();ctx.textAlign='left';ctx.fillStyle=p.onSubstrate;ctx.font='900 13px system-ui,sans-serif';ctx.fillText('VOIDCUT',40,22);ctx.fillStyle=p.accent;ctx.fillRect(40,29,48,4);ctx.fillStyle=p.onSubstrate;ctx.globalAlpha=.46;ctx.font='700 8px system-ui,sans-serif';ctx.fillText(`CUTFORM / ${vd2ModeName()}`,98,32);ctx.textAlign='right';ctx.fillText(`CH ${String(sim.chamber).padStart(2,'0')} / FIELD ${Math.round(sim.progress()*100)}%`,680,32);ctx.restore()}''',
'drawCompactHud':r'''function drawCompactHud(cleared,large,mag){const p=vd1Palette(),x=40,y=42,w=640,h=88,target=Math.round(sim.clearTarget()*100),ratio=Math.max(0,Math.min(1,cleared/target)),status=vd2CutStatus(),score=Math.round(shownScore).toLocaleString(),special=milestoneSpec(sim.plan?.milestone)||modifierSpec(sim.plan?.modifier);ctx.save();vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=p.accent;ctx.fillRect(x,y,7,h);ctx.strokeStyle=p.line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+218,y);ctx.lineTo(x+218,y+h);ctx.moveTo(x+475,y);ctx.lineTo(x+475,y+h);ctx.stroke();
ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText(`SCORE / ${vd2ModeName()}`,x+20,y+18);ctx.fillStyle=p.ink;ctx.font=`900 ${large?33:29+Math.min(3,scorePulse*1.5)}px system-ui,sans-serif`;ctx.fillText(score,x+20,y+52,180);if(hudMultiplier>1.001||hudCombo>0){const tag=`×${hudMultiplier.toFixed(1)} / ${hudCombo} COMBO`;ctx.fillStyle=p.accentAlt;ctx.fillRect(x+20,y+66,Math.min(168,ctx.measureText(tag).width+16),13);ctx.fillStyle=p.surfaceRaised;ctx.font='800 8px system-ui,sans-serif';ctx.fillText(tag,x+28,y+76)}else{ctx.fillStyle=p.inkMuted;ctx.font='700 8px system-ui,sans-serif';ctx.fillText('PRECISION CUTTING',x+20,y+76)}
const cx=x+238;ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('FIELD CLEAR',cx,y+18);ctx.textAlign='right';ctx.fillStyle=p.ink;ctx.font='900 25px system-ui,sans-serif';ctx.fillText(`${cleared}%`,x+455,y+30);ctx.textAlign='left';const bx=cx,by=y+43,bw=207,bh=20,steps=20,gap=2,cell=(bw-gap*(steps-1))/steps,filled=Math.round(ratio*steps);for(let i=0;i<steps;i++){ctx.fillStyle=i<filled?p.accent:p.line;ctx.globalAlpha=i<filled?1:.62;ctx.fillRect(bx+i*(cell+gap),by,cell,bh)}ctx.globalAlpha=1;const marker=bx+bw*Math.min(1,target/100);ctx.fillStyle=p.accentAlt;ctx.fillRect(Math.min(bx+bw-2,marker-1),by-4,2,bh+8);ctx.fillStyle=p.inkMuted;ctx.font='700 8px system-ui,sans-serif';ctx.fillText(`TARGET ${target}%`,cx,y+78);ctx.textAlign='right';ctx.fillStyle=status.color;ctx.font='800 8px system-ui,sans-serif';ctx.fillText(status.label,x+455,y+78);
const rx=x+495;ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText('CHAMBER',rx,y+18);ctx.fillStyle=p.ink;ctx.font=`900 ${large?39:35}px system-ui,sans-serif`;ctx.fillText(String(sim.chamber).padStart(2,'0'),rx,y+55);ctx.fillStyle=special?(sim.plan?.milestone?p.accentAlt:p.accent):p.inkMuted;ctx.font='800 8px system-ui,sans-serif';ctx.fillText(special?special.name:'STANDARD FIELD',rx,y+76,138);ctx.restore();vd2DrawCompetitiveStrip()}''',
'drawModifierField':r'''function drawModifierField(now){const id=sim.plan?.modifier,m=modifierSpec(id);if(!m||tutorialMode)return;const p=vd1Palette(),t=sim.chamberElapsed,motion=motionReduced()?0:1,shift=(now*.018*motion)%64;ctx.save();ctx.beginPath();ctx.rect(AX,AY,AW,AH);ctx.clip();ctx.strokeStyle=m.tier==='RARE'?p.accentAlt:p.accent;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1.25;ctx.globalAlpha=.075;if(id==='surge'){for(let x=AX-AH;x<AX+AW+AH;x+=72){ctx.beginPath();ctx.moveTo(x+shift,AY);ctx.lineTo(x+AH*.42+shift,AY+AH);ctx.stroke()}}else if(id==='stillpoint'){for(let r=80;r<500;r+=92){ctx.beginPath();ctx.arc(W/2,AY+AH/2,r,0,Math.PI*2);ctx.stroke()}}else if(id==='ramp'){for(let y=AY+80;y<AY+AH;y+=86){ctx.beginPath();ctx.moveTo(AX,y);ctx.lineTo(AX+AW*.45,y-30);ctx.lineTo(AX+AW,y-6);ctx.stroke()}}else if(id==='shift'){for(let y=AY+100;y<AY+AH;y+=180)for(let x=AX+100;x<AX+AW;x+=180){ctx.beginPath();ctx.moveTo(x-14,y);ctx.lineTo(x+14,y);ctx.moveTo(x,y-14);ctx.lineTo(x,y+14);ctx.stroke()}}else if(id==='overdrive'){ctx.lineWidth=2;for(let y=AY-40;y<AY+AH;y+=70){ctx.beginPath();ctx.moveTo(AX,y);ctx.lineTo(AX+AW,y+52);ctx.stroke()}}else if(id==='dense'){for(let y=AY+65;y<AY+AH;y+=105)for(let x=AX+65;x<AX+AW;x+=105)ctx.fillRect(x-2,y-2,4,4)}else if(id==='wide-beam'){ctx.globalAlpha=.12;ctx.fillRect(AX,AY,7,AH);ctx.fillRect(AX+AW-7,AY,7,AH)}else if(id==='deep'){ctx.globalAlpha=.065;for(let i=0;i<5;i++)ctx.strokeRect(AX+24+i*24,AY+24+i*24,AW-48-i*48,AH-48-i*48)}ctx.restore()}''',
'drawModifierBadge':r'''function drawModifierBadge(){const m=modifierSpec(sim.plan?.modifier);if(!m||tutorialMode||sim.plan?.milestone||sim.briefingRemaining>0)return;const p=vd1Palette(),w=286,h=42,x=52,y=151,accent=m.tier==='RARE'?p.accentAlt:p.accent;ctx.save();vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=accent;ctx.fillRect(x,y,6,h);ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='700 8px system-ui,sans-serif';ctx.fillText(`${m.tier} MODIFIER`,x+18,y+14);ctx.fillStyle=p.ink;ctx.font='900 14px system-ui,sans-serif';ctx.fillText(m.name,x+18,y+31,138);ctx.textAlign='right';ctx.fillStyle=accent;ctx.font='800 9px system-ui,sans-serif';ctx.fillText(modifierLiveState(sim.plan,sim.chamberElapsed),x+w-14,y+27,110);ctx.restore()}''',
'drawModifierBriefing':r'''function drawModifierBriefing(){const m=modifierSpec(sim.plan?.modifier);if(!m||sim.briefingRemaining<=0||tutorialMode||sim.plan?.milestone)return;const p=vd1Palette(),accent=m.tier==='RARE'?p.accentAlt:p.accent,total=1.15,elapsed=Math.max(0,total-sim.briefingRemaining),enter=motionReduced()?1:Math.min(1,elapsed/.24),leave=motionReduced()?1:Math.min(1,sim.briefingRemaining/.18),alpha=enter*leave,x=102+(1-enter)*18,y=H/2-106,w=516,h=184;ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=p.substrate;ctx.globalAlpha=.46*alpha;ctx.fillRect(AX,AY,AW,AH);ctx.globalAlpha=alpha;vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=accent;ctx.fillRect(x,y,9,h);ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='800 9px system-ui,sans-serif';ctx.fillText(`${m.tier} MODIFIER / CHAMBER ${sim.chamber}`,x+28,y+28);ctx.fillStyle=p.ink;ctx.font='900 31px system-ui,sans-serif';ctx.fillText(m.name,x+28,y+66,430);ctx.fillStyle=p.inkMuted;ctx.font='600 13px system-ui,sans-serif';vd2Wrap(m.desc,430,'600 13px system-ui,sans-serif').slice(0,2).forEach((q,i)=>ctx.fillText(q,x+28,y+99+i*20));ctx.strokeStyle=p.line;ctx.beginPath();ctx.moveTo(x+28,y+137);ctx.lineTo(x+w-28,y+137);ctx.stroke();ctx.fillStyle=accent;ctx.font='800 10px system-ui,sans-serif';ctx.fillText(`SCORE VALUE +${Math.round(((m.reward||1)-1)*100)}%`,x+28,y+160);ctx.fillStyle=p.inkMuted;ctx.textAlign='right';ctx.fillText('FIELD RULE ACTIVE',x+w-28,y+160);ctx.restore()}''',
'drawMilestoneField':r'''function drawMilestoneField(now){const id=sim.plan?.milestone,m=milestoneSpec(id);if(!m||tutorialMode)return;const p=vd1Palette(),motion=motionReduced()?0:1,phase=(now*.015*motion)%96;ctx.save();ctx.beginPath();ctx.rect(AX,AY,AW,AH);ctx.clip();ctx.strokeStyle=p.accentAlt;ctx.fillStyle=p.accentAlt;ctx.lineWidth=1.4;ctx.globalAlpha=.075;if(id==='first-breach'){for(let y=AY+80;y<AY+AH;y+=140){ctx.beginPath();ctx.moveTo(AX,y);ctx.lineTo(W/2-28,y+26);ctx.lineTo(W/2+28,y-26);ctx.lineTo(AX+AW,y);ctx.stroke()}}else if(id==='void-surge'){for(let i=0;i<6;i++)ctx.strokeRect(AX+50+i*34,AY+76+i*52,AW-100-i*68,AH-152-i*104)}else if(id==='fracture'){for(let i=0;i<8;i++){const y=AY+90+i*(AH-180)/7;ctx.beginPath();ctx.moveTo(AX-10,y);ctx.lineTo(AX+AW*.29,y-24);ctx.lineTo(AX+AW*.49,y+15);ctx.lineTo(AX+AW*.72,y-18);ctx.lineTo(AX+AW+10,y+12);ctx.stroke()}}else if(id==='event-horizon'){ctx.save();ctx.translate(W/2,AY+AH/2);ctx.rotate(Math.PI/4);for(let i=0;i<6;i++){const s=90+i*76+phase*.16;ctx.strokeRect(-s/2,-s/2,s,s)}ctx.restore();ctx.globalAlpha=.10;ctx.fillRect(W/2-3,AY,6,AH)}ctx.restore()}''',
'drawMilestoneBadge':r'''function drawMilestoneBadge(){const id=sim.plan?.milestone,m=milestoneSpec(id);if(!m||tutorialMode||sim.briefingRemaining>0)return;const p=vd1Palette(),w=372,h=48,x=52,y=151;ctx.save();vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=p.accentAlt;ctx.fillRect(x,y,8,h);ctx.textAlign='left';ctx.fillStyle=p.inkMuted;ctx.font='800 8px system-ui,sans-serif';ctx.fillText(`MILESTONE ${m.index}`,x+20,y+15);ctx.fillStyle=p.ink;ctx.font='900 16px system-ui,sans-serif';ctx.fillText(m.name,x+20,y+35,178);ctx.textAlign='right';ctx.fillStyle=p.accentAlt;ctx.font='800 9px system-ui,sans-serif';ctx.fillText(milestoneLiveState(sim.plan,sim.chamberElapsed),x+w-14,y+30,150);ctx.restore()}''',
'drawMilestoneBriefing':r'''function drawMilestoneBriefing(){const id=sim.plan?.milestone,m=milestoneSpec(id);if(!m||sim.briefingRemaining<=0||tutorialMode)return;const p=vd1Palette(),total=m.briefing||1.8,elapsed=Math.max(0,total-sim.briefingRemaining),enter=motionReduced()?1:Math.min(1,elapsed/.36),leave=motionReduced()?1:Math.min(1,sim.briefingRemaining/.24),alpha=enter*leave,x=76,y=H/2-146+(1-enter)*18,w=568,h=260;ctx.save();ctx.fillStyle=p.substrate;ctx.globalAlpha=.58*alpha;ctx.fillRect(AX,AY,AW,AH);ctx.globalAlpha=alpha;vd2HudPanel(x,y,w,h,p.surfaceRaised,p.edge,true);ctx.fillStyle=p.accentAlt;ctx.fillRect(x,y,12,h);ctx.fillStyle=p.accent;ctx.fillRect(x+12,y,w-12,7);ctx.textAlign='left';ctx.fillStyle=p.accentAlt;ctx.font='900 54px system-ui,sans-serif';ctx.fillText(String(m.index).padStart(2,'0'),x+36,y+78);ctx.fillStyle=p.inkMuted;ctx.font='800 9px system-ui,sans-serif';ctx.fillText('MILESTONE CHAMBER',x+142,y+34);ctx.fillStyle=p.ink;ctx.font='900 34px system-ui,sans-serif';ctx.fillText(m.name,x+142,y+78,380);ctx.fillStyle=p.inkMuted;ctx.font='600 13px system-ui,sans-serif';vd2Wrap(m.desc,382,'600 13px system-ui,sans-serif').slice(0,3).forEach((q,i)=>ctx.fillText(q,x+142,y+111+i*20));ctx.strokeStyle=p.line;ctx.beginPath();ctx.moveTo(x+28,y+181);ctx.lineTo(x+w-28,y+181);ctx.stroke();ctx.fillStyle=p.accent;ctx.font='900 11px system-ui,sans-serif';ctx.fillText(`${Math.round((m.clearTarget||CLEAR)*100)}% CLEAR`,x+30,y+211);ctx.fillStyle=p.ink;ctx.fillText(`+${(m.completionBonus||0).toLocaleString()} CLEAR BONUS`,x+160,y+211);ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText(m.live||'MILESTONE FIELD',x+30,y+236,480);ctx.restore()}''',
'drawPop':r'''function drawPop(q){const p=vd1Palette(),t=Math.min(1,q.age/q.dur),rise=(q.kind==='close'?32:24)*(1-Math.pow(1-t,2)),intro=Math.min(1,t/.12),out=Math.min(1,(1-t)*3),alpha=Math.min(out,intro*1.4),accent=q.kind==='close'?p.danger:q.kind==='divider'?p.accentAlt:q.kind==='tier'?p.accent:p.edge;ctx.save();ctx.globalAlpha=alpha;ctx.textAlign='center';ctx.font=`900 ${q.tier?16:23}px system-ui,sans-serif`;const tw=Math.min(300,Math.max(76,ctx.measureText(q.text).width+28)),x=q.x-tw/2,y=q.y-rise-(q.tier?25:29),h=q.sub?48:34;if(!save.settings.highContrast){ctx.fillStyle=p.shadow;ctx.globalAlpha=.18*alpha;ctx.fillRect(x+3,y+4,tw,h);ctx.globalAlpha=alpha}ctx.fillStyle=p.surfaceRaised;ctx.fillRect(x,y,tw,h);ctx.strokeStyle=p.edge;ctx.lineWidth=1.2;ctx.strokeRect(x+.5,y+.5,tw-1,h-1);ctx.fillStyle=accent;ctx.fillRect(x,y,tw,4);ctx.fillStyle=p.ink;ctx.fillText(q.text,q.x,y+23,tw-16);if(q.sub){ctx.fillStyle=p.inkMuted;ctx.font='700 9px system-ui,sans-serif';ctx.fillText(q.sub,q.x,y+39,tw-14)}ctx.restore()}''',
'draw':r'''function draw(now){const high=!!save.settings.highContrast,large=!!save.settings.largeUI,gameplayVisible=state==='play'||state==='replay'||state==='dying',p=vd1Palette();ctx.clearRect(0,0,W,H);ctx.fillStyle=p.substrate;ctx.fillRect(0,0,W,H);drawBackdrop(now);if(gameplayVisible){drawGameplayWordmark();const cleared=Math.min(100,Math.round(sim.removed/sim.area*100));if(tutorialMode)drawTutorialHud();else drawCompactHud(cleared,large,'');const cam=motionCamera(now);ctx.save();ctx.translate(W/2+cam.x,H/2+cam.y);ctx.rotate(cam.roll);ctx.scale(cam.scale,cam.scale);ctx.translate(-W/2,-H/2);drawFieldZones(high);drawModifierField(now);drawMilestoneField(now);for(const f of fx.collapses)drawCollapse(f);drawPermanentDividers(high,now);for(const l of fx.locks)drawDividerLock(l);if(save.settings.trails){for(const b of sim.balls)drawTrail(b,now)}for(const b of sim.balls)drawBall(b,now);if(tutorialMode)drawTutorialGuide(now);if(aim){const d=sub(aim.p,aim.o),distance=len(d);if(distance>=2){const q=sim.preview(aim.region,aim.o,d);if(q){const valid=distance>=minSwipe(),col=high?'#fff':valid?p.accent:p.line;ctx.save();ctx.setLineDash([10,8]);ctx.lineDashOffset=-(now*.022)%18;ctx.beginPath();ctx.moveTo(q.a.x,q.a.y);ctx.lineTo(q.b.x,q.b.y);ctx.strokeStyle=col;ctx.lineWidth=high?4:2;ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(aim.o.x,aim.o.y,minSwipe(),0,Math.PI*2);ctx.strokeStyle=col;ctx.globalAlpha=valid?.72:.42;ctx.lineWidth=1;ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=col;ctx.fillRect(aim.o.x-(valid?3:2),aim.o.y-(valid?3:2),valid?6:4,valid?6:4);ctx.restore()}}}if(sim.cut)drawCut(sim.cut,now,high);ctx.lineWidth=high?4:2.4;ctx.strokeStyle=p.edge;ctx.globalAlpha=1;pathPoly(sim.arena.v);ctx.stroke();drawBorderProgress(sim.progress());drawArenaSignatureFrame();for(const b of fx.bursts)drawFeedbackBurst(b);for(const r of fx.rings)drawRing(r);for(const q of fx.sparks)drawSpark(q);for(const q of fx.pops)drawPop(q);ctx.restore();drawModifierBadge();drawMilestoneBadge();drawModifierBriefing();drawMilestoneBriefing();if(transition)drawTransition(now)}if(gameplayVisible&&!save.settings.reducedMotion&&flash>.01){ctx.save();ctx.globalAlpha=Math.min(.045,flash*.026);ctx.fillStyle=p.accent;ctx.fillRect(0,0,W,H);ctx.restore()}if(gameplayVisible&&deathFlash>.01){ctx.save();ctx.globalAlpha=Math.min(.15,deathFlash*.13);ctx.fillStyle=p.danger;ctx.fillRect(0,0,W,H);ctx.restore()}if(gameplayVisible)drawScreenImpact(now,high)}'''
}

def replace_function(text,name,replacement):
    start=text.find(f'function {name}(')
    if start<0: raise SystemExit(f'missing function {name}')
    nxt=text.find('\nfunction ',start+1)
    if nxt<0: raise SystemExit(f'cannot find function boundary after {name}')
    return text[:start]+replacement+text[nxt:]

def main():
    text=INDEX.read_text(encoding='utf-8')
    if MARK in text:
        print('VD2 patch already applied; no changes.')
        return
    text=text.replace('<meta name="voidcut-visual-phase" content="VD1">','<meta name="voidcut-visual-phase" content="VD2">',1)
    anchor='const ARENA_THEMES={'
    pos=text.find(anchor)
    if pos<0: raise SystemExit('missing VD1 renderer insertion anchor')
    text=text[:pos]+HELPERS+'\n'+text[pos:]
    for name,replacement in REPL.items():
        text=replace_function(text,name,replacement)
    INDEX.write_text(text,encoding='utf-8')
    print('VD2 HUD patch applied')
    print('Replaced:',', '.join(REPL))

if __name__=='__main__':
    main()
