from pathlib import Path

root = Path(__file__).resolve().parents[2]
index = root / 'index.html'
client = root / 'leaderboard' / 'client' / 'global-leaderboard-runtime.js'
register = root / 'design' / 'V6_2_HARDENING_FIX_REGISTER.md'


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    return text.replace(old, new, 1)


old_identity_const = "const LEADERBOARD_IDENTITY_KEY='voidcut.leaderboard.identity.v1';\n"
new_identity_const = """const LEADERBOARD_IDENTITY_KEY='voidcut.leaderboard.identity.v1';
const LEADERBOARD_IDENTITY_BACKUP_KEY='voidcut.leaderboard.identity.backup.v1';
const LEADERBOARD_IDENTITY_TEST_KEY='voidcut.leaderboard.identity.storage-test.v1';
"""

old_identity_helpers = """function loadLeaderboardIdentity(){try{const x=JSON.parse(localStorage.getItem(LEADERBOARD_IDENTITY_KEY)||'null');return x&&typeof x.playerId==='string'&&typeof x.token==='string'&&typeof x.name==='string'?x:null}catch{return null}}
function storeLeaderboardIdentity(x){try{localStorage.setItem(LEADERBOARD_IDENTITY_KEY,JSON.stringify(x));return true}catch{return false}}
function clearLeaderboardIdentity(){try{localStorage.removeItem(LEADERBOARD_IDENTITY_KEY)}catch{}}
"""

new_identity_helpers = r"""function normalizeLeaderboardIdentity(x){if(!x||typeof x!=='object')return null;const playerId=String(x.playerId||'').trim(),name=String(x.name||'').trim().replace(/\s+/g,' '),token=String(x.token||'').trim();if(playerId.length<8||playerId.length>128||token.length<16||token.length>1024||!name||!/^[A-Za-z0-9 _-]{3,16}$/.test(name))return null;return{playerId,name,token}}
function leaderboardIdentityHash(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0').toUpperCase()}
function leaderboardIdentityEnvelope(x,savedAt=Date.now()){const d=normalizeLeaderboardIdentity(x);if(!d)return null;const payload=JSON.stringify(d);return JSON.stringify({f:1,savedAt:Math.max(1,Math.floor(Number(savedAt)||Date.now())),h:leaderboardIdentityHash(payload),d})}
function parseLeaderboardIdentitySnapshot(raw){if(!raw)return null;try{const p=JSON.parse(raw);if(p&&p.f===1){const d=normalizeLeaderboardIdentity(p.d);if(!d||!Number.isFinite(p.savedAt)||p.savedAt<=0||typeof p.h!=='string'||leaderboardIdentityHash(JSON.stringify(d))!==p.h)return null;return{data:d,savedAt:Math.floor(p.savedAt),legacy:false}}const d=normalizeLeaderboardIdentity(p);return d?{data:d,savedAt:0,legacy:true}:null}catch{return null}}
function leaderboardIdentityStorageSelfTest(){const token=`${Date.now()}:${Math.random()}`;try{localStorage.setItem(LEADERBOARD_IDENTITY_TEST_KEY,token);const ok=localStorage.getItem(LEADERBOARD_IDENTITY_TEST_KEY)===token;localStorage.removeItem(LEADERBOARD_IDENTITY_TEST_KEY);return ok}catch{try{localStorage.removeItem(LEADERBOARD_IDENTITY_TEST_KEY)}catch{}return false}}
function sameLeaderboardIdentity(a,b){return!!a&&!!b&&a.playerId===b.playerId&&a.name===b.name&&a.token===b.token}
function writeLeaderboardIdentityCopy(key,envelope){try{localStorage.setItem(key,envelope);return localStorage.getItem(key)===envelope}catch{return false}}
function repairLeaderboardIdentityCopies(x,savedAt=Date.now()){const d=normalizeLeaderboardIdentity(x),env=d?leaderboardIdentityEnvelope(d,savedAt):null;if(!d||!env)return false;const backupOk=writeLeaderboardIdentityCopy(LEADERBOARD_IDENTITY_BACKUP_KEY,env),primaryOk=writeLeaderboardIdentityCopy(LEADERBOARD_IDENTITY_KEY,env),p=parseLeaderboardIdentitySnapshot(primaryOk?localStorage.getItem(LEADERBOARD_IDENTITY_KEY):null),b=parseLeaderboardIdentitySnapshot(backupOk?localStorage.getItem(LEADERBOARD_IDENTITY_BACKUP_KEY):null);return!!primaryOk&&!!backupOk&&sameLeaderboardIdentity(p?.data,d)&&sameLeaderboardIdentity(b?.data,d)}
function readStoredLeaderboardIdentity(){let primary=null,backup=null;try{primary=parseLeaderboardIdentitySnapshot(localStorage.getItem(LEADERBOARD_IDENTITY_KEY));backup=parseLeaderboardIdentitySnapshot(localStorage.getItem(LEADERBOARD_IDENTITY_BACKUP_KEY))}catch{return null}const candidates=[primary&&{...primary,priority:2},backup&&{...backup,priority:1}].filter(Boolean).sort((a,b)=>b.savedAt-a.savedAt||b.priority-a.priority);if(!candidates.length)return null;const chosen=candidates[0],needsRepair=chosen.legacy||!primary||!backup||!sameLeaderboardIdentity(primary.data,chosen.data)||!sameLeaderboardIdentity(backup.data,chosen.data);if(needsRepair)repairLeaderboardIdentityCopies(chosen.data,chosen.savedAt||Date.now());return chosen.data}
function loadLeaderboardIdentity(){const ident=readStoredLeaderboardIdentity();if(ident)leaderboardIdentityMemory=ident;return ident}
function storeLeaderboardIdentity(x){const d=normalizeLeaderboardIdentity(x);if(!d)return false;leaderboardIdentityMemory=d;if(!leaderboardIdentityStorageSelfTest())return false;const savedAt=Date.now();if(!repairLeaderboardIdentityCopies(d,savedAt))return false;const loaded=readStoredLeaderboardIdentity();return sameLeaderboardIdentity(loaded,d)}
function clearLeaderboardIdentity(){leaderboardIdentityMemory=null;for(const key of [LEADERBOARD_IDENTITY_KEY,LEADERBOARD_IDENTITY_BACKUP_KEY,LEADERBOARD_IDENTITY_TEST_KEY])try{localStorage.removeItem(key)}catch{}}
"""

old_profile = "async function createLeaderboardProfileFromCard(){const input=$('leaderboardNameInput'),button=$('leaderboardJoinButton'),status=$('leaderboardJoinStatus'),name=(input?.value||'').trim().replace(/\\s+/g,' ');if(!/^[A-Za-z0-9 _-]{3,16}$/.test(name)){status.textContent='Use 3–16 letters, numbers, spaces, _ or -.';return}button.disabled=true;status.textContent='CREATING PROFILE…';try{const data=await leaderboardRequest('/profile/create',{method:'POST',body:JSON.stringify({name})},false);if(!data?.player?.id||!data?.token)throw new Error('Invalid profile response');storeLeaderboardIdentity({playerId:data.player.id,name:data.player.name,token:data.token});status.textContent=leaderboardSubmissionQueue.length?`PROFILE READY • VERIFYING ${leaderboardSubmissionQueue.length} QUEUED RUN${leaderboardSubmissionQueue.length===1?'':'S'}…`:'PROFILE READY';await drainLeaderboardSubmissionQueue()}catch(err){status.textContent=err?.code==='name-taken'?'NAME ALREADY TAKEN':String(err?.message||'PROFILE CREATION FAILED').toUpperCase()}finally{button.disabled=false}}"
new_profile = "async function createLeaderboardProfileFromCard(){const input=$('leaderboardNameInput'),button=$('leaderboardJoinButton'),status=$('leaderboardJoinStatus'),name=(input?.value||'').trim().replace(/\\s+/g,' ');if(!/^[A-Za-z0-9 _-]{3,16}$/.test(name)){status.textContent='Use 3–16 letters, numbers, spaces, _ or -.';return}if(!leaderboardIdentityStorageSelfTest()){status.textContent='LOCAL STORAGE UNAVAILABLE • PROFILE NOT CREATED';return}button.disabled=true;status.textContent='CREATING PROFILE…';try{const data=await leaderboardRequest('/profile/create',{method:'POST',body:JSON.stringify({name})},false);if(!data?.player?.id||!data?.token)throw new Error('Invalid profile response');const ident=normalizeLeaderboardIdentity({playerId:data.player.id,name:data.player.name,token:data.token});if(!ident)throw new Error('Invalid profile response');if(!storeLeaderboardIdentity(ident)){leaderboardIdentityMemory=ident;status.textContent='PROFILE CREATED • IDENTITY STORAGE FAILED • EXPORT SAVE BEFORE CLOSING';return}status.textContent=leaderboardSubmissionQueue.length?`PROFILE READY • VERIFYING ${leaderboardSubmissionQueue.length} QUEUED RUN${leaderboardSubmissionQueue.length===1?'':'S'}…`:'PROFILE READY';await drainLeaderboardSubmissionQueue()}catch(err){status.textContent=err?.code==='name-taken'?'NAME ALREADY TAKEN':String(err?.message||'PROFILE CREATION FAILED').toUpperCase()}finally{button.disabled=false}}"

old_export = "function exportFullSave(){const data=normalizeSave(save),payload=JSON.stringify(data),env={f:2,v:SAVE_SCHEMA,h:saveHash(payload),d:data};return`VC35SAVE:${utf8ToB64Url(JSON.stringify(env))}`}"
new_export = "function exportFullSave(){const data=normalizeSave(save),identity=normalizeLeaderboardIdentity(loadLeaderboardIdentity()||leaderboardIdentityMemory),payload={d:data,i:identity},env={f:3,v:SAVE_SCHEMA,h:saveHash(JSON.stringify(payload)),...payload};return`VC35SAVE:${utf8ToB64Url(JSON.stringify(env))}`}"

old_import = "function importFullSave(code){try{const t=(code||'').trim();if(t.length>2000000)return null;const prefix=t.startsWith('VC35SAVE:')?'VC35SAVE:':t.startsWith('VC28SAVE:')?'VC28SAVE:':null;if(!prefix)return null;const env=JSON.parse(b64UrlToUtf8(t.slice(prefix.length)));if(![1,2].includes(env?.f)||!env.d||typeof env.h!=='string')return null;const original=JSON.stringify(env.d);if(saveHash(original)!==env.h&&saveHash(JSON.stringify(normalizeSave(env.d)))!==env.h)return null;return normalizeSave(env.d)}catch{return null}}"
new_import = "function importFullSave(code){try{const t=(code||'').trim();if(t.length>2000000)return null;const prefix=t.startsWith('VC35SAVE:')?'VC35SAVE:':t.startsWith('VC28SAVE:')?'VC28SAVE:':null;if(!prefix)return null;const env=JSON.parse(b64UrlToUtf8(t.slice(prefix.length)));if(![1,2,3].includes(env?.f)||!env.d||typeof env.h!=='string')return null;if(env.f===3){const identity=env.i==null?null:normalizeLeaderboardIdentity(env.i);if(env.i!=null&&!identity)return null;const originalPackage=JSON.stringify({d:env.d,i:identity});const normalizedPackage=JSON.stringify({d:normalizeSave(env.d),i:identity});if(saveHash(originalPackage)!==env.h&&saveHash(normalizedPackage)!==env.h)return null;if(identity&&!storeLeaderboardIdentity(identity))leaderboardIdentityMemory=identity;return normalizeSave(env.d)}const original=JSON.stringify(env.d);if(saveHash(original)!==env.h&&saveHash(JSON.stringify(normalizeSave(env.d)))!==env.h)return null;return normalizeSave(env.d)}catch{return null}}"

# Source client identity hardening.
c = client.read_text(encoding='utf-8')
c = replace_once(c, old_identity_const, new_identity_const, 'client identity constants')
c = replace_once(c, "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null;\n", "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null,leaderboardIdentityMemory=null;\n", 'client identity memory')
c = replace_once(c, old_identity_helpers, new_identity_helpers, 'client identity helpers')
c = replace_once(c, old_profile, new_profile, 'client profile durability')
client.write_text(c, encoding='utf-8')

# Shipped inline runtime identity hardening and portable ownership envelope.
s = index.read_text(encoding='utf-8')
s = replace_once(s, old_identity_const, new_identity_const, 'inline identity constants')
s = replace_once(s, "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null;\n", "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null,leaderboardIdentityMemory=null;\n", 'inline identity memory')
s = replace_once(s, old_identity_helpers, new_identity_helpers, 'inline identity helpers')
s = replace_once(s, old_profile, new_profile, 'inline profile durability')
s = replace_once(s, old_export, new_export, 'portable full-save export')
s = replace_once(s, old_import, new_import, 'portable full-save import')
index.write_text(s, encoding='utf-8')

r = register.read_text(encoding='utf-8')
old_010 = '| VC-010 | MEDIUM | Profile creation ignores failure to persist/read back local leaderboard identity, potentially orphaning the username/token relationship. | F10 | OPEN |'
new_010 = '| VC-010 | MEDIUM | Profile creation ignores failure to persist/read back local leaderboard identity, potentially orphaning the username/token relationship. | F10 | FIXED — VERIFYING |'
old_027 = '| VC-027 | LOW | Leaderboard identity is outside the normal full-save export/import path; profile ownership is not portable/recoverable through the current backup flow. | F10/F24 | OPEN |'
new_027 = '| VC-027 | LOW | Leaderboard identity is outside the normal full-save export/import path; profile ownership is not portable/recoverable through the current backup flow. | F10/F24 | FIXED — VERIFYING; F24 AUDIT PENDING |'
if r.count(old_010) != 1 or r.count(old_027) != 1:
    raise SystemExit('F10 register markers missing')
r = r.replace(old_010, new_010, 1).replace(old_027, new_027, 1)
r += '''\n## F10 implementation record — leaderboard identity durability and ownership portability\n\n- Leaderboard ownership credentials now use validated, checksummed primary and backup local-storage snapshots instead of one unchecked raw local-storage value.\n- The existing primary key remains unchanged for compatibility; legacy raw identity objects are accepted, normalized and repaired into the new redundant envelope format on read.\n- Identity reads choose the newest valid primary/backup snapshot and repair a missing, stale or corrupt counterpart.\n- Identity writes run a storage preflight, write both copies, immediately read back both copies and return success only when both round-trip to the exact normalized identity.\n- Server-side profile creation is not attempted when the browser fails the local identity-storage preflight.\n- After the server returns a new token, queued ranked submissions are not drained unless the identity was durably written and read back successfully.\n- If storage fails in the narrow interval after server profile creation, the credential is retained only in an emergency in-memory holder and the UI instructs the player to export their full save before closing; authenticated requests do not silently treat that volatile credential as durable ownership.\n- A server `401` clears the primary identity, backup identity, storage-test residue and emergency in-memory copy together, so an invalid token cannot resurrect from backup.\n- Full-save export now emits backward-compatible `VC35SAVE` envelope format `f:3`, whose checksum covers both normalized game-save data and an optional leaderboard identity credential block.\n- Full-save import still accepts legacy `f:1` / `f:2` codes unchanged. Valid `f:3` imports restore leaderboard ownership only after the complete credential-bearing package checksum validates.\n- Imported ownership uses the same redundant write/readback path; if destination storage is unavailable, the imported credential remains in emergency memory so it can be immediately re-exported rather than silently lost.\n- Save schema remains 17 because leaderboard credentials are envelope-level ownership metadata, not gameplay/save-state fields. F24 remains the destructive migration/corruption audit gate for the completed portability path.\n- No Worker, replay verifier, replay format, ticket TTL, physics, scoring or leaderboard ordering changed in F10.\n'''
register.write_text(r, encoding='utf-8')
