from pathlib import Path

root = Path(__file__).resolve().parents[2]
paths = [root / 'index.html', root / 'leaderboard' / 'src' / 'index.js']
old = "function compareLeaderboardRank(a,b){const scoreA=Number.isFinite(Number(a?.score))?Number(a.score):0,scoreB=Number.isFinite(Number(b?.score))?Number(b.score):0;if(scoreA!==scoreB)return scoreA>scoreB?-1:1;const chamberA=Number.isFinite(Number(a?.chamber))?Number(a.chamber):1,chamberB=Number.isFinite(Number(b?.chamber))?Number(b.chamber):1;if(chamberA!==chamberB)return chamberA>chamberB?-1:1;const timeA=Number.isFinite(Number(a?.time))?Number(a.time):Infinity,timeB=Number.isFinite(Number(b?.time))?Number(b.time):Infinity;if(timeA!==timeB)return timeA<timeB?-1:1;const updatedA=Number.isFinite(Number(a?.updatedAt))?Number(a.updatedAt):Infinity,updatedB=Number.isFinite(Number(b?.updatedAt))?Number(b.updatedAt):Infinity;if(updatedA!==updatedB)return updatedA<updatedB?-1:1;const idA=String(a?.id??''),idB=String(b?.id??'');if(idA!==idB)return idA<idB?-1:1;return 0}"
new = "function compareLeaderboardRank(a,b){const scoreA=Number.isFinite(Number(a?.score))?Number(a.score):0,scoreB=Number.isFinite(Number(b?.score))?Number(b.score):0;if(scoreA!==scoreB)return scoreA>scoreB?-1:1;const chamberA=a?.chamber==null?1:Number.isFinite(Number(a.chamber))?Number(a.chamber):1,chamberB=b?.chamber==null?1:Number.isFinite(Number(b.chamber))?Number(b.chamber):1;if(chamberA!==chamberB)return chamberA>chamberB?-1:1;const timeA=a?.time==null?Infinity:Number.isFinite(Number(a.time))?Number(a.time):Infinity,timeB=b?.time==null?Infinity:Number.isFinite(Number(b.time))?Number(b.time):Infinity;if(timeA!==timeB)return timeA<timeB?-1:1;const updatedA=a?.updatedAt==null?Infinity:Number.isFinite(Number(a.updatedAt))?Number(a.updatedAt):Infinity,updatedB=b?.updatedAt==null?Infinity:Number.isFinite(Number(b.updatedAt))?Number(b.updatedAt):Infinity;if(updatedA!==updatedB)return updatedA<updatedB?-1:1;const idA=String(a?.id??''),idB=String(b?.id??'');if(idA!==idB)return idA<idB?-1:1;return 0}"
for path in paths:
    s = path.read_text(encoding='utf-8')
    if s.count(old) != 1:
        raise SystemExit(f'{path}: expected old comparator exactly once, found {s.count(old)}')
    path.write_text(s.replace(old, new, 1), encoding='utf-8')
