from pathlib import Path

root = Path(__file__).resolve().parents[2]
index = root / 'index.html'
client = root / 'leaderboard' / 'client' / 'global-leaderboard-runtime.js'
f8test = root / 'leaderboard' / 'scripts' / 'test-ranked-start-ticket-source.mjs'
register = root / 'design' / 'V6_2_HARDENING_FIX_REGISTER.md'


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    return text.replace(old, new, 1)


queue_constants = """const LEADERBOARD_SUBMISSION_QUEUE_KEY='voidcut.leaderboard.submissions.v1';
const LEADERBOARD_SUBMISSION_QUEUE_LIMIT=16;
const LEADERBOARD_QUEUE_RETRY_MS=15000;
"""

queue_block = r"""function normalizeLeaderboardSubmissionQueue(raw,now=Date.now()){if(!Array.isArray(raw))return[];const out=[],seen=new Set;for(const item of raw){const ticket=item?.ticket,replay=item?.replay,id=String(item?.id||ticket?.ticketId||''),expiresAt=Number(ticket?.expiresAt)||0;if(!id||seen.has(id)||!ticket||String(ticket.ticketId||'')!==id||!replay||typeof replay!=='object'||!Number.isFinite(expiresAt)||expiresAt<=now+1000)continue;seen.add(id);out.push({id,ticket,replay,queuedAt:Number(item?.queuedAt)||now})}return out.slice(-LEADERBOARD_SUBMISSION_QUEUE_LIMIT)}
function loadLeaderboardSubmissionQueue(){try{return normalizeLeaderboardSubmissionQueue(JSON.parse(localStorage.getItem(LEADERBOARD_SUBMISSION_QUEUE_KEY)||'[]'))}catch{try{localStorage.removeItem(LEADERBOARD_SUBMISSION_QUEUE_KEY)}catch{}return[]}}
function persistLeaderboardSubmissionQueue(queue=leaderboardSubmissionQueue){const clean=normalizeLeaderboardSubmissionQueue(queue);leaderboardSubmissionQueue=clean;try{const text=JSON.stringify(clean);localStorage.setItem(LEADERBOARD_SUBMISSION_QUEUE_KEY,text);return localStorage.getItem(LEADERBOARD_SUBMISSION_QUEUE_KEY)===text}catch{return false}}
function enqueueLeaderboardSubmission(replay,ticket){const id=String(ticket?.ticketId||''),expiresAt=Number(ticket?.expiresAt)||0;if(!id||!replay||typeof replay!=='object'||!Number.isFinite(expiresAt)||expiresAt<=Date.now()+1000)return'invalid';const base=normalizeLeaderboardSubmissionQueue(leaderboardSubmissionQueue).filter(x=>x.id!==id);if(base.length>=LEADERBOARD_SUBMISSION_QUEUE_LIMIT)return'full';return persistLeaderboardSubmissionQueue([...base,{id,ticket,replay,queuedAt:Date.now()}])?'queued':'volatile'}
function removeLeaderboardSubmission(id){leaderboardSubmissionQueue=leaderboardSubmissionQueue.filter(x=>x.id!==id);const ok=persistLeaderboardSubmissionQueue(leaderboardSubmissionQueue);if(!leaderboardSubmissionQueue.length&&leaderboardQueueRetryTimer!==null){clearTimeout(leaderboardQueueRetryTimer);leaderboardQueueRetryTimer=null}return ok}
function terminalLeaderboardSubmissionError(err){return[400,403,404,409,410,413,422].includes(Number(err?.status)||0)}
function scheduleLeaderboardQueueRetry(){if(leaderboardQueueRetryTimer!==null||!leaderboardSubmissionQueue.length||!loadLeaderboardIdentity()||navigator.onLine===false)return;leaderboardQueueRetryTimer=setTimeout(()=>{leaderboardQueueRetryTimer=null;void drainLeaderboardSubmissionQueue()},LEADERBOARD_QUEUE_RETRY_MS)}
async function submitLeaderboardQueueEntry(entry){return leaderboardRequest(`/run/submit/${encodeURIComponent(entry.ticket.ticketId)}`,{method:'POST',body:JSON.stringify(entry.replay)},true)}
async function drainLeaderboardSubmissionQueue(){if(leaderboardQueueDrainPromise)return leaderboardQueueDrainPromise;leaderboardSubmissionQueue=normalizeLeaderboardSubmissionQueue(leaderboardSubmissionQueue);persistLeaderboardSubmissionQueue(leaderboardSubmissionQueue);if(!leaderboardSubmissionQueue.length)return null;if(!loadLeaderboardIdentity()){showLeaderboardJoin(`${leaderboardSubmissionQueue.length} ranked run${leaderboardSubmissionQueue.length===1?' is':'s are'} safely queued. Choose a public name to submit ${leaderboardSubmissionQueue.length===1?'it':'them'}.`);return null}leaderboardQueueDrainPromise=(async()=>{while(leaderboardSubmissionQueue.length){const entry=leaderboardSubmissionQueue[0];if(Number(entry.ticket?.expiresAt)<=Date.now()+1000){removeLeaderboardSubmission(entry.id);appendLeaderboardResult('GLOBAL QUEUED RUN EXPIRED');continue}try{appendLeaderboardResult('GLOBAL VERIFYING');const data=await submitLeaderboardQueueEntry(entry);removeLeaderboardSubmission(entry.id);ui.newBest.textContent=(ui.newBest.textContent||'').replace(/(?: • )?GLOBAL VERIFYING/g,'');hideLeaderboardJoin();const rank=data?.rank?`GLOBAL #${Number(data.rank).toLocaleString()}`:'GLOBAL VERIFIED';appendLeaderboardResult(data?.personalBest?`${rank} • PERSONAL BEST`:rank)}catch(err){ui.newBest.textContent=(ui.newBest.textContent||'').replace(/(?: • )?GLOBAL VERIFYING/g,'');if(err?.status===401){clearLeaderboardIdentity();showLeaderboardJoin(`${leaderboardSubmissionQueue.length} queued ranked run${leaderboardSubmissionQueue.length===1?' needs':'s need'} a valid leaderboard identity before submission.`);break}if(terminalLeaderboardSubmissionError(err)){removeLeaderboardSubmission(entry.id);appendLeaderboardResult('GLOBAL QUEUED RUN REJECTED');continue}appendLeaderboardResult('GLOBAL SUBMISSION QUEUED');scheduleLeaderboardQueueRetry();break}}if(!leaderboardSubmissionQueue.length)hideLeaderboardJoin()})().finally(()=>{leaderboardQueueDrainPromise=null});return leaderboardQueueDrainPromise}
function queueLeaderboardSubmission(replay,ticket){if(!replay||!ticket)return false;const result=enqueueLeaderboardSubmission(replay,ticket);if(result==='invalid')return false;if(result==='full'){appendLeaderboardResult('GLOBAL QUEUE FULL');return false}if(result==='volatile')appendLeaderboardResult('GLOBAL QUEUE STORAGE FAILED');if(loadLeaderboardIdentity())void drainLeaderboardSubmissionQueue();else showLeaderboardJoin(`${leaderboardSubmissionQueue.length} ranked run${leaderboardSubmissionQueue.length===1?' is':'s are'} queued. Choose one public name to submit ${leaderboardSubmissionQueue.length===1?'it':'them'}.`);return result==='queued'}
leaderboardSubmissionQueue=loadLeaderboardSubmissionQueue();
window.addEventListener('online',()=>void drainLeaderboardSubmissionQueue());
"""

old_profile = "async function createLeaderboardProfileFromCard(){const input=$('leaderboardNameInput'),button=$('leaderboardJoinButton'),status=$('leaderboardJoinStatus'),name=(input?.value||'').trim().replace(/\\s+/g,' ');if(!/^[A-Za-z0-9 _-]{3,16}$/.test(name)){status.textContent='Use 3–16 letters, numbers, spaces, _ or -.';return}button.disabled=true;status.textContent='CREATING PROFILE…';try{const data=await leaderboardRequest('/profile/create',{method:'POST',body:JSON.stringify({name})},false);if(!data?.player?.id||!data?.token)throw new Error('Invalid profile response');storeLeaderboardIdentity({playerId:data.player.id,name:data.player.name,token:data.token});status.textContent='PROFILE READY • VERIFYING RUN…';if(pendingLeaderboardSubmission)await submitLeaderboardRun(pendingLeaderboardSubmission.replay,pendingLeaderboardSubmission.ticket)}catch(err){status.textContent=err?.code==='name-taken'?'NAME ALREADY TAKEN':String(err?.message||'PROFILE CREATION FAILED').toUpperCase()}finally{button.disabled=false}}"
new_profile = "async function createLeaderboardProfileFromCard(){const input=$('leaderboardNameInput'),button=$('leaderboardJoinButton'),status=$('leaderboardJoinStatus'),name=(input?.value||'').trim().replace(/\\s+/g,' ');if(!/^[A-Za-z0-9 _-]{3,16}$/.test(name)){status.textContent='Use 3–16 letters, numbers, spaces, _ or -.';return}button.disabled=true;status.textContent='CREATING PROFILE…';try{const data=await leaderboardRequest('/profile/create',{method:'POST',body:JSON.stringify({name})},false);if(!data?.player?.id||!data?.token)throw new Error('Invalid profile response');storeLeaderboardIdentity({playerId:data.player.id,name:data.player.name,token:data.token});status.textContent=leaderboardSubmissionQueue.length?`PROFILE READY • VERIFYING ${leaderboardSubmissionQueue.length} QUEUED RUN${leaderboardSubmissionQueue.length===1?'':'S'}…`:'PROFILE READY';await drainLeaderboardSubmissionQueue()}catch(err){status.textContent=err?.code==='name-taken'?'NAME ALREADY TAKEN':String(err?.message||'PROFILE CREATION FAILED').toUpperCase()}finally{button.disabled=false}}"
old_submit = "async function submitLeaderboardRun(replay,ticket){if(!replay||!ticket)return;const ident=loadLeaderboardIdentity();if(!ident){pendingLeaderboardSubmission={replay,ticket};showLeaderboardJoin();return}try{appendLeaderboardResult('GLOBAL VERIFYING');const data=await leaderboardRequest(`/run/submit/${encodeURIComponent(ticket.ticketId)}`,{method:'POST',body:JSON.stringify(replay)},true);pendingLeaderboardSubmission=null;hideLeaderboardJoin();const rank=data?.rank?`GLOBAL #${Number(data.rank).toLocaleString()}`:'GLOBAL VERIFIED';ui.newBest.textContent=(ui.newBest.textContent||'').replace(/(?: • )?GLOBAL VERIFYING/g,'');appendLeaderboardResult(data?.personalBest?`${rank} • PERSONAL BEST`:rank)}catch(err){ui.newBest.textContent=(ui.newBest.textContent||'').replace(/(?: • )?GLOBAL VERIFYING/g,'');if(err?.status===401){clearLeaderboardIdentity();pendingLeaderboardSubmission={replay,ticket};showLeaderboardJoin('Your local leaderboard identity expired. Choose a name to create a new one and submit this run.')}else appendLeaderboardResult('GLOBAL SUBMISSION FAILED')}}\nfunction queueLeaderboardSubmission(replay,ticket){if(!replay||!ticket)return;pendingLeaderboardSubmission={replay,ticket};if(loadLeaderboardIdentity())void submitLeaderboardRun(replay,ticket);else showLeaderboardJoin()}\n"

# Source client.
c = client.read_text(encoding='utf-8')
c = replace_once(c, "const RANKED_START_WAIT_MS=2000;\n", "const RANKED_START_WAIT_MS=2000;\n" + queue_constants, 'client queue constants')
c = replace_once(c, "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,pendingLeaderboardSubmission=null;\n", "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null;\n", 'client queue state')
anchor = "async function acquireLeaderboardTicket(waitMs=RANKED_START_WAIT_MS){const ready=takeLeaderboardTicket();if(ready)return{ticket:ready,reason:null};const request=prefetchLeaderboardTicket();let timer=null;const outcome=await Promise.race([request.then(()=>'settled'),new Promise(resolve=>{timer=setTimeout(()=>resolve('timeout'),Math.max(0,Number(waitMs)||0))})]);if(timer!==null)clearTimeout(timer);const ticket=takeLeaderboardTicket();if(ticket)return{ticket,reason:null};return{ticket:null,reason:outcome==='timeout'?'LEADERBOARD TIMEOUT':'LEADERBOARD UNAVAILABLE'}}\n"
c = replace_once(c, anchor, anchor + queue_block, 'client queue block')
c = replace_once(c, old_profile, new_profile, 'client profile queue drain')
c = replace_once(c, old_submit, '', 'client volatile submit path removal')
client.write_text(c, encoding='utf-8')

# Shipped inline runtime.
s = index.read_text(encoding='utf-8')
s = replace_once(s, "const RANKED_START_WAIT_MS=2000;\n", "const RANKED_START_WAIT_MS=2000;\n" + queue_constants, 'inline queue constants')
s = replace_once(s, "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,pendingLeaderboardSubmission=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null;\n", "let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null;\n", 'inline queue state')
s = replace_once(s, anchor, anchor + queue_block, 'inline queue block')
s = replace_once(s, old_profile, new_profile, 'inline profile queue drain')
s = replace_once(s, old_submit, '', 'inline volatile submit path removal')
s = replace_once(s, "function showMenu(){\nvoid prefetchLeaderboardTicket();\n", "function showMenu(){\nvoid prefetchLeaderboardTicket();\nvoid drainLeaderboardSubmissionQueue();\n", 'menu queue drain')
index.write_text(s, encoding='utf-8')

# Keep F8 regression focused on the ranked-start state after the F9 architecture removes the old single-slot variable.
t = f8test.read_text(encoding='utf-8')
t = replace_once(
    t,
    '"let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,pendingLeaderboardSubmission=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null;",',
    '"let leaderboardTicket=null,leaderboardTicketPromise=null,activeLeaderboardTicket=null,rankedRunInvalidReason=null,rankedRunInvalidNoticeShown=false,rankedTimingIntegrity=null,rankedStartPromise=null,leaderboardSubmissionQueue=[],leaderboardQueueDrainPromise=null,leaderboardQueueRetryTimer=null;",',
    'F8 state invariant update',
)
f8test.write_text(t, encoding='utf-8')

r = register.read_text(encoding='utf-8')
old_row = '| VC-009 | MEDIUM | Only one in-memory pending leaderboard submission is retained; later runs/reloads/network failure can lose a valid submission. | F9 | OPEN |'
new_row = '| VC-009 | MEDIUM | Only one in-memory pending leaderboard submission is retained; later runs/reloads/network failure can lose a valid submission. | F9 | FIXED — VERIFYING |'
if r.count(old_row) != 1:
    raise SystemExit('VC-009 register marker missing')
r = r.replace(old_row, new_row, 1)
r += '''\n## F9 implementation record — persistent multi-entry leaderboard submission queue\n\n- The single volatile `pendingLeaderboardSubmission` slot has been removed.\n- Ranked submissions are now enqueued under the dedicated `voidcut.leaderboard.submissions.v1` local-storage key before any network submission attempt.\n- The queue retains up to 16 distinct ticket/replay entries and never evicts an existing valid entry merely to make room for a later run; a full queue is surfaced explicitly as `GLOBAL QUEUE FULL`.\n- Queue writes are read back immediately. If persistent storage is unavailable, the entry remains in the current in-memory queue as a best-effort volatile fallback and the UI surfaces `GLOBAL QUEUE STORAGE FAILED`.\n- Queue loading rejects malformed entries, de-duplicates ticket IDs and prunes tickets whose server expiry has passed. Corrupt JSON is discarded rather than preventing startup.\n- Submissions drain sequentially so multiple completed runs cannot overwrite each other or create parallel submission storms.\n- Success removes only the successfully handled ticket. The server's verified-ticket idempotence makes an accidental retry after a failed local queue cleanup safe.\n- HTTP 400/403/404/409/410/413/422 responses are treated as terminal for that ticket and remove only that entry; the queue then continues.\n- HTTP 401 preserves the queue, clears the invalid local identity and waits for profile recovery.\n- HTTP 429, network failures and 5xx responses preserve the queue and schedule a bounded 15-second retry while online.\n- Browser `online` and normal menu entry both trigger queue draining, so reload/offline recovery resumes automatically once a valid identity and connectivity are present.\n- Creating a leaderboard profile drains every queued run rather than submitting only the most recent one.\n- No Worker, replay verifier, ticket TTL, scoring, physics, save schema or leaderboard ordering changed in F9.\n'''
register.write_text(r, encoding='utf-8')
